openapi: 3.0.3
info:
  title: maven-tst
  description: |-
    maven test
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-example.com/rest/maven-tst/0.0.1"
paths: {}
